{
 "title": "Orchestrators",
 "tags": [
  "Blockchain",
  "Cosmos"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cosmos", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(orchestrator_information{}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "eth-orchestrator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors count total increase",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(orchestrator_errors_count_total{instance=~\"$instance\",job=~\"eth-orchestrator\"}[$__range])"
    }
   ]
  },
  {
   "title": "Warnings count total increase",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(orchestrator_warnings_count_total{instance=~\"$instance\",job=~\"eth-orchestrator\"}[$__range])"
    }
   ]
  },
  {
   "title": "Last checked contract nonce",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestrator_information{gauge=\"last_checked_event\",instance=~\"$instance\",job=~\"eth-orchestrator\"}"
    }
   ]
  },
  {
   "title": "Latest cosmos block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestrator_information{gauge=\"latest_cosmos_block\",instance=~\"$instance\",job=~\"eth-orchestrator\"}"
    }
   ]
  },
  {
   "title": "Latest eth block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestrator_information{gauge=\"latest_eth_block\",instance=~\"$instance\",job=~\"eth-orchestrator\"}"
    }
   ]
  }
 ]
}